apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - /deployment/pv.yaml
  - /deployment/pvc.yaml
  - /deployment/hpa.yaml
  - /deployment/secret.yaml
  - /deployment/frontend.yaml
  - /deployment/backend.yaml
  - /deployment/webapp.yaml
  - /deployment/hpawebapp.yaml
  